"""
    Arbeitsagentur Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br>Die Authentifizierung funktioniert über die clientId:<br><br>clientId: jobboerse-jobsuche<br><br>Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.  # noqa: E501

    The version of the OpenAPI document: 2.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.jobsuche.model.job_search_response_stellenangebote_inner_arbeitsort_koordinaten import (
    JobSearchResponseStellenangeboteInnerArbeitsortKoordinaten,
)

from deutschland import jobsuche

globals()[
    "JobSearchResponseStellenangeboteInnerArbeitsortKoordinaten"
] = JobSearchResponseStellenangeboteInnerArbeitsortKoordinaten
from deutschland.jobsuche.model.job_search_response_stellenangebote_inner_arbeitsort import (
    JobSearchResponseStellenangeboteInnerArbeitsort,
)


class TestJobSearchResponseStellenangeboteInnerArbeitsort(unittest.TestCase):
    """JobSearchResponseStellenangeboteInnerArbeitsort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSearchResponseStellenangeboteInnerArbeitsort(self):
        """Test JobSearchResponseStellenangeboteInnerArbeitsort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobSearchResponseStellenangeboteInnerArbeitsort()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
