"""
Arbeitsagentur Jobsuche API

Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br>Die Authentifizierung funktioniert über die clientId:<br><br>clientId: jobboerse-jobsuche<br><br>Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.  # noqa: E501

The version of the OpenAPI document: 2.1.0
Contact: kontakt@bund.dev
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.jobsuche.model.job_details_eintrittszeitraum import (
    JobDetailsEintrittszeitraum,
)

from deutschland import jobsuche


class TestJobDetailsEintrittszeitraum(unittest.TestCase):
    """JobDetailsEintrittszeitraum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobDetailsEintrittszeitraum(self):
        """Test JobDetailsEintrittszeitraum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobDetailsEintrittszeitraum()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
