"""
    Arbeitsagentur Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br>Die Authentifizierung funktioniert über die clientId:<br><br>clientId: jobboerse-jobsuche<br><br>Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.  # noqa: E501

    The version of the OpenAPI document: 2.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.jobsuche.model.job_details_arbeitsorte_inner_koordinaten import (
    JobDetailsArbeitsorteInnerKoordinaten,
)

from deutschland import jobsuche


class TestJobDetailsArbeitsorteInnerKoordinaten(unittest.TestCase):
    """JobDetailsArbeitsorteInnerKoordinaten unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobDetailsArbeitsorteInnerKoordinaten(self):
        """Test JobDetailsArbeitsorteInnerKoordinaten"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobDetailsArbeitsorteInnerKoordinaten()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
