"""
    Arbeitsagentur Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8. **Achtung**: der OAuth header muss 'OAuthAccessToken' heißen.<br><br> Die API verfügt außerdem nicht über ein gültiges TLS Zertifikat. Deswegen sollte die TLS-Validierung deaktiviert werden.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.jobsuche.model.job_search_response_embedded_jobs_items_links_arbeitgeberlogo import (
    JobSearchResponseEmbeddedJobsItemsLinksArbeitgeberlogo,
)
from deutschland.jobsuche.model.job_search_response_embedded_jobs_items_links_details import (
    JobSearchResponseEmbeddedJobsItemsLinksDetails,
)
from deutschland.jobsuche.model.job_search_response_embedded_jobs_items_links_jobdetails import (
    JobSearchResponseEmbeddedJobsItemsLinksJobdetails,
)

from deutschland import jobsuche

globals()[
    "JobSearchResponseEmbeddedJobsItemsLinksArbeitgeberlogo"
] = JobSearchResponseEmbeddedJobsItemsLinksArbeitgeberlogo
globals()[
    "JobSearchResponseEmbeddedJobsItemsLinksDetails"
] = JobSearchResponseEmbeddedJobsItemsLinksDetails
globals()[
    "JobSearchResponseEmbeddedJobsItemsLinksJobdetails"
] = JobSearchResponseEmbeddedJobsItemsLinksJobdetails
from deutschland.jobsuche.model.job_search_response_embedded_jobs_items_links import (
    JobSearchResponseEmbeddedJobsItemsLinks,
)


class TestJobSearchResponseEmbeddedJobsItemsLinks(unittest.TestCase):
    """JobSearchResponseEmbeddedJobsItemsLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSearchResponseEmbeddedJobsItemsLinks(self):
        """Test JobSearchResponseEmbeddedJobsItemsLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobSearchResponseEmbeddedJobsItemsLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
