"""
    Arbeitsagentur Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8. **Achtung**: der OAuth header muss 'OAuthAccessToken' heißen.<br><br> Die API verfügt außerdem nicht über ein gültiges TLS Zertifikat. Deswegen sollte die TLS-Validierung deaktiviert werden.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.jobsuche.model.job_search_response_aggregierungen import (
    JobSearchResponseAggregierungen,
)
from deutschland.jobsuche.model.job_search_response_embedded import (
    JobSearchResponseEmbedded,
)
from deutschland.jobsuche.model.job_search_response_facetten_inner import (
    JobSearchResponseFacettenInner,
)
from deutschland.jobsuche.model.job_search_response_links import JobSearchResponseLinks
from deutschland.jobsuche.model.job_search_response_page import JobSearchResponsePage
from deutschland.jobsuche.model.job_search_response_parser_result import (
    JobSearchResponseParserResult,
)

from deutschland import jobsuche

globals()["JobSearchResponseAggregierungen"] = JobSearchResponseAggregierungen
globals()["JobSearchResponseEmbedded"] = JobSearchResponseEmbedded
globals()["JobSearchResponseFacettenInner"] = JobSearchResponseFacettenInner
globals()["JobSearchResponseLinks"] = JobSearchResponseLinks
globals()["JobSearchResponsePage"] = JobSearchResponsePage
globals()["JobSearchResponseParserResult"] = JobSearchResponseParserResult
from deutschland.jobsuche.model.job_search_response import JobSearchResponse


class TestJobSearchResponse(unittest.TestCase):
    """JobSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSearchResponse(self):
        """Test JobSearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobSearchResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
